"""Evaluate both local SLMs on fill-in-the-blank questions.

The input CSV must contain ``question`` and ``answer`` columns. Multiple valid
answers may be separated by a vertical bar in the answer field. Each model is
asked to finish with ``ANSWER: <text>``; grading ignores capitalization,
surrounding whitespace, and punctuation.
"""

from __future__ import annotations

import argparse
import csv
import gc
import re
import unicodedata
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Sequence, Tuple

import mlx.core as mx
from mlx_lm import generate, load
from mlx_lm.sample_utils import make_sampler

from ask_models import MODELS


DEFAULT_TEST_FILE = Path("qa6-world-history.csv")


@dataclass(frozen=True)
class FillBlankTestCase:
    """One fill-in-the-blank question and its accepted answers.

    Attributes:
        question: Question containing a blank for the model to complete.
        accepted_answers: Valid answers, with the canonical answer first.
    """

    question: str
    accepted_answers: Tuple[str, ...]


@dataclass(frozen=True)
class FillBlankTestResult:
    """Outcome of one model's response to one fill-in-the-blank question.

    Attributes:
        question: Question presented to the model.
        expected: Canonical expected answer.
        actual: Text extracted from the model's final answer marker, or
            ``None`` when no marker was found.
        raw_response: Complete generated model response.
        passed: Whether the normalized response matches an accepted answer.
    """

    question: str
    expected: str
    actual: Optional[str]
    raw_response: str
    passed: bool


def normalize_answer(answer: str) -> str:
    """Normalize a short text answer for deterministic comparison.

    Args:
        answer: Expected or generated answer text.

    Returns:
        Case-folded words separated by single spaces, with punctuation removed.
    """
    # NFKC makes visually equivalent Unicode forms compare consistently.
    normalized = unicodedata.normalize("NFKC", answer).casefold()
    normalized = re.sub(r"[^\w\s]", " ", normalized)
    return " ".join(normalized.split())


def load_test_cases(csv_path: Path) -> List[FillBlankTestCase]:
    """Read and validate fill-in-the-blank cases from CSV.

    Args:
        csv_path: UTF-8 CSV path containing ``question`` and ``answer`` columns.

    Returns:
        Validated cases in their original CSV order.

    Raises:
        FileNotFoundError: If ``csv_path`` does not exist.
        ValueError: If columns, questions, or answers are missing.
    """
    cases: List[FillBlankTestCase] = []
    with csv_path.open("r", encoding="utf-8-sig", newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        if reader.fieldnames is None or not {"question", "answer"}.issubset(
            reader.fieldnames
        ):
            raise ValueError("CSV must contain 'question' and 'answer' columns")

        for line_number, row in enumerate(reader, start=2):
            question = (row.get("question") or "").strip()
            answers = tuple(
                answer.strip()
                for answer in (row.get("answer") or "").split("|")
                if answer.strip()
            )
            if not question:
                raise ValueError(f"CSV line {line_number} has an empty question")
            if not answers:
                raise ValueError(f"CSV line {line_number} has no valid answer")
            cases.append(
                FillBlankTestCase(question=question, accepted_answers=answers)
            )

    if not cases:
        raise ValueError("CSV must contain at least one test case")
    return cases


def parse_final_answer(response: str) -> Optional[str]:
    """Extract the last `ANSWER:` value from generated text.

    Args:
        response: Raw text generated by a model.

    Returns:
        Text following the final answer marker, or ``None`` if no marker exists.
    """
    matches = re.findall(
        r"ANSWER\s*:\s*([^\r\n]+)", response, flags=re.IGNORECASE
    )
    if not matches:
        return None
    return matches[-1].strip()


def answer_matches(actual: Optional[str], accepted_answers: Sequence[str]) -> bool:
    """Determine whether generated text equals one accepted answer.

    Args:
        actual: Parsed model answer, or ``None`` after a parsing failure.
        accepted_answers: Valid text answers for the question.

    Returns:
        ``True`` when normalized values match; otherwise ``False``.
    """
    if actual is None:
        return False
    normalized_actual = normalize_answer(actual)
    return any(
        normalized_actual == normalize_answer(expected)
        for expected in accepted_answers
    )


def test_model(
    model_path: Path,
    test_cases: Sequence[FillBlankTestCase],
    max_tokens: int = 64,
) -> List[FillBlankTestResult]:
    """Run all fill-in-the-blank cases against one local model.

    Args:
        model_path: Directory containing the MLX model and tokenizer.
        test_cases: Ordered questions and accepted answers.
        max_tokens: Maximum generated tokens per answer.

    Returns:
        One graded result for each supplied test case.

    Raises:
        FileNotFoundError: If required model files are unavailable.
        ValueError: If MLX cannot load the model or format its prompt.
    """
    model, tokenizer = load(str(model_path))
    sampler = make_sampler(temp=0.0)
    results: List[FillBlankTestResult] = []

    try:
        for test_case in test_cases:
            instruction = (
                "Fill in the blank in this world history question. On the "
                "final line, write only ANSWER: <answer>.\n\n"
                f"Question: {test_case.question}"
            )
            prompt = tokenizer.apply_chat_template(
                [{"role": "user", "content": instruction}],
                tokenize=False,
                add_generation_prompt=True,
            )
            raw_response = generate(
                model,
                tokenizer,
                prompt=prompt,
                max_tokens=max_tokens,
                sampler=sampler,
                verbose=False,
            ).strip()
            actual = parse_final_answer(raw_response)
            results.append(
                FillBlankTestResult(
                    question=test_case.question,
                    expected=test_case.accepted_answers[0],
                    actual=actual,
                    raw_response=raw_response,
                    passed=answer_matches(actual, test_case.accepted_answers),
                )
            )
    finally:
        del model, tokenizer
        gc.collect()
        mx.clear_cache()

    return results


def print_report(model_name: str, results: Sequence[FillBlankTestResult]) -> None:
    """Print detailed outcomes and aggregate accuracy for one model.

    Args:
        model_name: Human-readable model name used as the heading.
        results: Graded fill-in-the-blank results.

    Returns:
        None. The report is written to standard output.
    """
    passed_count = sum(result.passed for result in results)
    print(f"\n{model_name}\n{'=' * len(model_name)}")
    for index, result in enumerate(results, start=1):
        status = "PASS" if result.passed else "FAIL"
        actual = result.actual or "Unrecognized"
        print(
            f"{index:2}. {status} | Expected: {result.expected} "
            f"| Actual: {actual}\n    {result.question}"
        )

    total_count = len(results)
    accuracy = (passed_count / total_count * 100) if total_count else 0.0
    print(f"\nResult: {passed_count}/{total_count} correct ({accuracy:.1f}%)")


def run_tests(csv_path: Path, max_tokens: int = 64) -> None:
    """Evaluate both configured models with a fill-in-the-blank CSV.

    Args:
        csv_path: Path to the fill-in-the-blank test data.
        max_tokens: Maximum generated tokens per answer.

    Returns:
        None. A report for each model is printed to standard output.

    Raises:
        FileNotFoundError: If the CSV or a model directory is missing.
        ValueError: If the CSV or model input is invalid.
    """
    test_cases = load_test_cases(csv_path)
    missing_models = [str(path) for path in MODELS.values() if not path.is_dir()]
    if missing_models:
        raise FileNotFoundError(
            "Missing model directories: " + ", ".join(missing_models)
        )

    for model_name, model_path in MODELS.items():
        results = test_model(model_path, test_cases, max_tokens=max_tokens)
        print_report(model_name, results)


def main() -> None:
    """Parse command-line options and run the fill-in-the-blank test.

    Args:
        None. Arguments are read from the command line.

    Returns:
        None. Reports are written to standard output.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "csv_path",
        nargs="?",
        type=Path,
        default=DEFAULT_TEST_FILE,
        help=f"test CSV path (default: {DEFAULT_TEST_FILE})",
    )
    parser.add_argument(
        "--max-tokens",
        type=int,
        default=64,
        help="maximum generated tokens per answer (default: 64)",
    )
    args = parser.parse_args()
    run_tests(args.csv_path, max_tokens=args.max_tokens)


if __name__ == "__main__":
    main()
