"""Evaluate both local SLMs with questions and answers from a CSV file.

The input CSV must contain ``question`` and ``answer`` columns. Each answer must
be either ``True`` or ``False``. Models are loaded sequentially to limit unified
memory use, while each model remains loaded for all questions in the test set.
"""

from __future__ import annotations

import argparse
import csv
import gc
import re
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Sequence

import mlx.core as mx
from mlx_lm import generate, load
from mlx_lm.sample_utils import make_sampler

from ask_models import MODELS


# Keep the default test location explicit so callers can supply other suites.
DEFAULT_TEST_FILE = Path("data/qa1-true-false.csv")


@dataclass(frozen=True)
class TestCase:
    """One expected true-or-false answer from the input dataset.

    Attributes:
        question: Factual statement that the model must classify.
        expected: Canonical expected label, either ``True`` or ``False``.
    """

    question: str
    expected: str


@dataclass(frozen=True)
class TestResult:
    """Outcome of asking one model one test question.

    Attributes:
        question: Factual statement presented to the model.
        expected: Correct answer supplied by the test dataset.
        actual: Normalized model answer, or ``None`` when no label was found.
        raw_response: Complete text generated by the model.
        passed: Whether ``actual`` matches ``expected``.
    """

    question: str
    expected: str
    actual: Optional[str]
    raw_response: str
    passed: bool


def load_test_cases(csv_path: Path) -> List[TestCase]:
    """Read and validate true-or-false cases from a CSV file.

    Args:
        csv_path: Path to a UTF-8 CSV containing ``question`` and ``answer``
            columns.

    Returns:
        Test cases in the same order in which they appear in the CSV file.

    Raises:
        FileNotFoundError: If ``csv_path`` does not exist.
        ValueError: If columns, questions, or true-or-false answers are invalid.
    """
    cases: List[TestCase] = []

    # ``utf-8-sig`` also accepts CSV files exported with a UTF-8 byte-order mark.
    with csv_path.open("r", encoding="utf-8-sig", newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        if reader.fieldnames is None or not {"question", "answer"}.issubset(
            reader.fieldnames
        ):
            raise ValueError("CSV must contain 'question' and 'answer' columns")

        for line_number, row in enumerate(reader, start=2):
            question = (row.get("question") or "").strip()
            answer = (row.get("answer") or "").strip().capitalize()
            if not question:
                raise ValueError(f"CSV line {line_number} has an empty question")
            if answer not in {"True", "False"}:
                raise ValueError(
                    f"CSV line {line_number} answer must be True or False"
                )
            cases.append(TestCase(question=question, expected=answer))

    if not cases:
        raise ValueError("CSV must contain at least one test case")
    return cases


def parse_true_false(response: str) -> Optional[str]:
    """Extract the first true-or-false label from generated text.

    Args:
        response: Raw text produced by a model.

    Returns:
        Canonical ``True`` or ``False`` when found; otherwise ``None``.
    """
    # Word boundaries prevent accidental matches inside words such as "untrue".
    match = re.search(r"\b(true|false)\b", response, flags=re.IGNORECASE)
    return match.group(1).capitalize() if match else None


def test_model(
    model_path: Path, test_cases: Sequence[TestCase], max_tokens: int = 8
) -> List[TestResult]:
    """Run every test case against one local SLM.

    Args:
        model_path: Directory containing the local MLX model and tokenizer.
        test_cases: Ordered cases to present to the model.
        max_tokens: Maximum number of tokens generated for each answer.

    Returns:
        One result per test case, preserving the input order.

    Raises:
        FileNotFoundError: If required model files are unavailable.
        ValueError: If MLX cannot load the model or format a prompt.
    """
    model, tokenizer = load(str(model_path))
    results: List[TestResult] = []

    # Temperature zero selects the highest-probability token and makes repeated
    # QA runs deterministic for a fixed model and MLX-LM version.
    sampler = make_sampler(temp=0.0)
    try:
        for test_case in test_cases:
            instruction = (
                "Determine whether the following statement is true or false. "
                "Respond with exactly True or False.\n\n"
                f"Statement: {test_case.question}"
            )
            prompt = tokenizer.apply_chat_template(
                [{"role": "user", "content": instruction}],
                tokenize=False,
                add_generation_prompt=True,
            )
            raw_response = generate(
                model,
                tokenizer,
                prompt=prompt,
                max_tokens=max_tokens,
                sampler=sampler,
                verbose=False,
            ).strip()
            actual = parse_true_false(raw_response)
            results.append(
                TestResult(
                    question=test_case.question,
                    expected=test_case.expected,
                    actual=actual,
                    raw_response=raw_response,
                    passed=actual == test_case.expected,
                )
            )
    finally:
        # Release unified memory even when inference raises an exception.
        del model, tokenizer
        gc.collect()
        mx.clear_cache()

    return results


def print_report(model_name: str, results: Sequence[TestResult]) -> None:
    """Print per-question outcomes and aggregate accuracy for one model.

    Args:
        model_name: Human-readable model name used as the report heading.
        results: Completed results returned by :func:`test_model`.

    Returns:
        None. The report is written to standard output.
    """
    passed_count = sum(result.passed for result in results)
    total_count = len(results)

    print(f"\n{model_name}\n{'=' * len(model_name)}")
    for index, result in enumerate(results, start=1):
        status = "PASS" if result.passed else "FAIL"
        actual = result.actual or f"Unrecognized ({result.raw_response!r})"
        print(
            f"{index:2}. {status} | Expected: {result.expected:<5} "
            f"| Actual: {actual}\n    {result.question}"
        )

    accuracy = (passed_count / total_count * 100) if total_count else 0.0
    print(f"\nResult: {passed_count}/{total_count} correct ({accuracy:.1f}%)")


def run_tests(csv_path: Path, max_tokens: int = 8) -> None:
    """Load a CSV test suite, evaluate both configured SLMs, and report results.

    Args:
        csv_path: Path to the true-or-false test CSV.
        max_tokens: Maximum number of generated tokens per model answer.

    Returns:
        None. A separate report for each configured model is printed.

    Raises:
        FileNotFoundError: If the CSV or a model is missing.
        ValueError: If test data or model input is invalid.
    """
    test_cases = load_test_cases(csv_path)
    missing_models = [str(path) for path in MODELS.values() if not path.is_dir()]
    if missing_models:
        raise FileNotFoundError(
            "Missing model directories: " + ", ".join(missing_models)
        )

    for model_name, model_path in MODELS.items():
        results = test_model(model_path, test_cases, max_tokens=max_tokens)
        print_report(model_name, results)


def main() -> None:
    """Parse evaluator command-line arguments and run the selected test suite.

    Args:
        None. Arguments are read from the process command line.

    Returns:
        None. Test reports are written to standard output.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "csv_path",
        nargs="?",
        type=Path,
        default=DEFAULT_TEST_FILE,
        help=f"test CSV path (default: {DEFAULT_TEST_FILE})",
    )
    parser.add_argument(
        "--max-tokens",
        type=int,
        default=8,
        help="maximum generated tokens per answer (default: 8)",
    )
    args = parser.parse_args()
    run_tests(args.csv_path, max_tokens=args.max_tokens)


# Keep imports side-effect free so test helpers can be reused by future suites.
if __name__ == "__main__":
    main()
